Adding apache configuration files in secure way to the installation
git-svn-id: https://pycsw.svn.sourceforge.net/svnroot/pycsw/trunk@502 f6d6ccb1-4906-4145-b9cb-3503ec0a5639

diff --git a/etc/dist/debian/postinst b/etc/dist/debian/postinst
--- a/etc/dist/debian/postinst
+++ b/etc/dist/debian/postinst
@@ -1,39 +1,51 @@
 #!/bin/sh
 # postinst script for pycsw
+#
+# see: dh_installdeb(1)
 
-PYCSW_APACHE_CONF=/etc/apache2/conf.d/pycsw
-WEB=/var/www
-PYCSW_HOME=$WEB/pycsw
+set -e
 
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-cat << EOF > "$PYCSW_APACHE_CONF"
+install() {
+    cd /var/www/pycsw/tester
+    python ./gen_html.py > index.html
+    /etc/init.d/apache2 force-reload
 
-        <Directory $PYCSW_HOME>
-	    Options FollowSymLinks +ExecCGI
-	    Allow from all
-	    AddHandler cgi-script .py
-        </Directory>
+}
 
-EOF
+case "$1" in
+    configure)
+        install
+    ;;
 
-if [ ! -e /usr/share/applications/pycsw.desktop ] ; then
-   cat << EOF > /usr/share/applications/pycsw.desktop
-[Desktop Entry]
-Type=Application
-Encoding=UTF-8
-Name=pycsw
-Comment=pycsw catalog server
-Categories=Application;Education;Geography;
-Exec=firefox http://localhost/pycsw/tester/index.html
-Icon=/var/www/pycsw/docs/_static/pycsw-logo.png
-Terminal=false
-StartupNotify=false
-Categories=Education;Geography;
-EOF
-fi
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
 
-python $PYCSW_HOME/tester/gen_html.py > $PYCSW_HOME/tester/index.html
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
-/etc/init.d/apache2 force-reload
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
+
+
+
+
+
